#!/bin/sh
# postinst script for lazyfier

SHORTCUT_NAME=$HOME/.config/autostart/lazyfier.desktop

echo "[Desktop Entry]" > $SHORTCUT_NAME
echo "Encoding=UTF-8" >> $SHORTCUT_NAME
echo "Type=Application" >> $SHORTCUT_NAME
echo "Name=Lazyfier" >> $SHORTCUT_NAME
echo "Comment='Lazyfier remote controller server'" >> $SHORTCUT_NAME
echo "Exec=/opt/lazyfier_6/LazyfierServer" >> $SHORTCUT_NAME
echo "StartupNotify=false" >> $SHORTCUT_NAME
echo "Terminal=false" >> $SHORTCUT_NAME
echo "Path=/opt/lazyfier_6/LazyfierServer" >> $SHORTCUT_NAME

/opt/lazyfier_6/LazyfierServer &

chmod u+s /sbin/shutdown

exit 0
